name: go

on:
  push:
    paths:
      - go/**
      - .github/workflows/go.yml
  workflow_dispatch:

permissions:
  contents: read

# 同じワークフロー/同じブランチで実行中ジョブがあれば自動停止させる
# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go/go.mod'

      - run: go build -o isuconquest
        working-directory: go
